[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
reqwest = { version = "0.12", features = ["json"], optional = true }
serde = { version = "1.0", features = ["derive"] }
dioxus-fullstack = { workspace = true, optional = true }
lumen-blocks = { git = "https://github.com/Leaf-Computer/lumen-blocks.git", tag = "v0.2.0" }

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "dep:reqwest", "dep:dioxus-fullstack"]
