[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
# 共享库
shared = { path = "../shared" }

# 异步 trait
async-trait = { workspace = true }

# 基础工具库
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
