[workspace]
resolver = "2"
members = [
  "packages/ui",
  "packages/web",
  # "packages/desktop",
  # "packages/mobile",
  "packages/io",
]

[workspace.dependencies]
dioxus = { version = "0.7.0" }

# workspace
ui = { path = "packages/ui" }
io = { path = "packages/io" }
